import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import { motion } from "framer-motion";
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
//import { useEffect } from 'react'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'




// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  
    // Load the Spline Viewer script on the client side
    
  return (
    <>
      <Head>
        <title>Krishnandu's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> 
      <TransitionEffect/>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
      
      <Layout className='pt-0 md:pt-16 sm:pt-8'>
       <div className='flex items-center justify-between w-full lg:flex-col'>
        <div className='w-1/2 md:w-full'>
        <motion.div
  whileHover={{ scale: 1.05 }}
  initial={{ opacity: 0, y: 30 }}
  whileInView={{ opacity: 1, y: 0 }}
  transition={{ duration: 0.5 }}
>
        <div className="hover:scale-105 hover:brightness-110 transition-all duration-300">
        <Image src={profilePic} alt='CoderImage' className='w-full h-auto lg:hidden md:inline-block md:w-full' priority sizes='(max-width: 768px) 100vw,(max-width:1200px) 50vw, 50vw' />
        </div>
        </motion.div>
          </div>
          <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
          
           <AnimatedText text="Turning Vision Into Reality With Code And Design." className='!text-6xl !text-left 
           xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
           '/>
           <p
           className='my-4 text-base font-medium md:text-sm sm:text-xs'
           >As a skilled full-stack developer, I am dedicated to turning ideas into innovative web applications. 
           Explore my latest projects and articles, showcasing my expertise in React.js and web development.
           </p>
           <div className='flex items-center self-start mt-2 lg:self-center'>
            <Link href="/dummy.pdf" target={'-blank'}
            className='flex items-center bg-dark dark:bg-light dark:text-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light dark:hover:bg-dark dark:hover:text-light hover:text-dark 
            border-2 border-solid border-transparent dark:hover:border-light hover:border-dark 
            md:p-2 md:px-4 md:text-base
            ' download={true}
            >Resume<LinkArrow className='w-6 ml-1'/></Link>
            <Link href="mailto:krishnandu.work@gmail.com" target={'-blank'}
            className='ml-4 text-lg font-medium capitalize text-dark dark:text-light underline
            md:text-base
            '
            >Contact</Link>

           </div>
           </div>
        </div>
      </Layout>
      <HireMe/>
      <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
        <Image src={lightBulb} alt="Krishnandu" className='w-full h-auto'/>
      </div>
      </main>
    </>
  )
}
